<style>
    .finance-page,.finance-page *{box-sizing:border-box}
    .finance-page{color:var(--onyx-text,#f5f7fa);display:grid;font-family:Poppins,system-ui,sans-serif;font-size:12px;gap:14px;width:100%}
    .finance-header,.finance-card,.finance-panel{background:linear-gradient(180deg,rgba(255,255,255,.035),rgba(255,255,255,.012)),var(--onyx-surface,#101923);border:1px solid rgba(255,255,255,.18);border-radius:0;box-shadow:0 10px 28px rgba(0,0,0,.22)}
    .finance-header{align-items:center;display:flex;gap:14px;justify-content:space-between;padding:16px}
    .finance-title{align-items:center;display:flex;gap:12px;min-width:0}.finance-icon{align-items:center;background:var(--onyx-accent,#ffffff);color:#050506;display:inline-flex;flex:0 0 38px;height:38px;justify-content:center;width:38px}
    .finance-header h1{color:#fff;font-size:18px;font-weight:900;line-height:1.15;margin:0 0 3px}.finance-muted{color:var(--onyx-muted,#8d99a8);font-size:11px;font-weight:700;line-height:1.45}
    .finance-actions,.finance-filters{align-items:center;display:flex;flex-wrap:wrap;gap:8px}
    .finance-button,.finance-icon-button{align-items:center;background:var(--onyx-accent,#ffffff);border:1px solid var(--onyx-accent,#ffffff);color:#050506;cursor:pointer;display:inline-flex;font:inherit;font-size:11px;font-weight:900;gap:8px;justify-content:center;min-height:36px;padding:0 12px;text-decoration:none;text-transform:uppercase;white-space:nowrap}
    .finance-button.secondary,.finance-icon-button{background:rgba(255,255,255,.025);border-color:rgba(255,255,255,.2);color:var(--onyx-text,#f5f7fa)}
    .finance-grid{display:grid;gap:12px;grid-template-columns:repeat(4,minmax(0,1fr))}.finance-card{min-width:0;padding:13px}.finance-card span,.finance-field label,.finance-table th{color:var(--onyx-muted,#8d99a8);display:block;font-size:10px;font-weight:900;letter-spacing:.5px;text-transform:uppercase}.finance-card strong{color:#fff;display:block;font-size:18px;font-weight:900;margin-top:6px;overflow-wrap:anywhere}
    .finance-panel{padding:15px}.finance-panel-head{align-items:center;border-bottom:1px solid rgba(255,255,255,.06);display:flex;gap:10px;justify-content:space-between;margin-bottom:13px;padding-bottom:11px}.finance-panel h2{color:#fff;font-size:13px;font-weight:900;margin:0;text-transform:uppercase}
    .finance-table-wrap{overflow-x:auto}.finance-table{border-collapse:collapse;min-width:820px;width:100%}.finance-table th,.finance-table td{border-bottom:1px solid rgba(255,255,255,.06);font-size:12px;padding:10px;text-align:left;vertical-align:middle}.finance-table td{color:var(--onyx-text,#f5f7fa);font-weight:650}.finance-table tbody tr:hover{background:rgba(255,255,255,.055)}.finance-table-title{color:#fff;display:block;font-size:12px;font-weight:900;margin-bottom:3px}
    .finance-badge{border:1px solid rgba(255,255,255,.32);color:#d8d8de;display:inline-flex;font-size:10px;font-weight:900;padding:5px 7px;text-transform:uppercase;white-space:nowrap}.finance-badge.success{border-color:rgba(143,240,195,.32);color:#8ff0c3}.finance-badge.warning{border-color:rgba(255,210,122,.32);color:#ffd27a}.finance-badge.danger{border-color:rgba(255,138,138,.32);color:#ff8a8a}
    .finance-form{display:grid;gap:12px;grid-template-columns:repeat(4,minmax(0,1fr))}.finance-field{display:grid;gap:6px;min-width:0}.finance-field.full{grid-column:1/-1}.finance-field.double{grid-column:span 2}.finance-field input,.finance-field select,.finance-field textarea{background:#0b141e;border:1px solid rgba(255,255,255,.18);color:#fff;font:inherit;font-size:12px;font-weight:700;min-height:38px;padding:8px 10px;width:100%}.finance-field textarea{min-height:82px;resize:vertical}.finance-field select option{background:#050506;color:#fff}
    .finance-alert{background:linear-gradient(180deg,rgba(255,255,255,.035),rgba(255,255,255,.012)),var(--onyx-surface,#101923);border:1px solid rgba(255,255,255,.18);color:#fff;font-size:12px;font-weight:800;padding:10px 12px}.finance-alert.success{border-color:rgba(143,240,195,.28);color:#8ff0c3}.finance-alert.warning{border-color:rgba(255,210,122,.28);color:#ffd27a}.finance-alert.danger{border-color:rgba(255,138,138,.28);color:#ff8a8a}
    .finance-split{display:grid;gap:12px;grid-template-columns:minmax(0,1.2fr) minmax(280px,.8fr)}
    @media(max-width:1180px){.finance-grid,.finance-form,.finance-split{grid-template-columns:repeat(2,minmax(0,1fr))}}
    @media(max-width:720px){.finance-header{align-items:flex-start;flex-direction:column}.finance-grid,.finance-form,.finance-split{grid-template-columns:1fr}.finance-field.double{grid-column:1}.finance-button{width:100%}.finance-actions,.finance-filters{align-items:stretch;width:100%}.finance-actions>*{flex:1 1 100%}}
    .finance-page{gap:10px}.finance-header{align-items:center!important;gap:8px!important;min-height:0!important;padding:8px 10px!important}.finance-title{gap:8px!important}.finance-icon{flex:0 0 28px!important;font-size:10px!important;height:28px!important;width:28px!important}.finance-header h1{font-size:14px!important;font-weight:800!important;line-height:1.1!important;margin:0 0 1px!important}.finance-muted{font-size:10px!important;font-weight:400!important;line-height:1.25!important}.finance-button,.finance-icon-button{font-size:10px!important;font-weight:700!important;gap:6px!important;min-height:30px!important;padding:0 9px!important}.finance-panel,.finance-card{padding:10px!important}.finance-panel-head{margin-bottom:9px!important;padding-bottom:8px!important}.finance-panel h2{font-size:11px!important;font-weight:700!important}.finance-card strong{font-size:14px!important;font-weight:700!important;margin-top:3px!important}
</style>
