<?php

namespace App\Support;

class PermissionCatalog
{
    public static function groups(): array
    {
        return [
            'Dashboard' => [
                'dashboard.view' => 'View dashboard',
                'dashboard.sensitive' => 'View sensitive figures',
            ],
            'Enterprise Foundation' => [
                'foundation.view' => 'View enterprise foundation workspace',
                'foundation.company.manage' => 'Manage company configuration',
                'foundation.approvals.manage' => 'Manage approval requests',
                'foundation.notifications.view' => 'View system notifications',
                'foundation.events.view' => 'View domain event ledger',
                'foundation.documents.view' => 'View document foundation register',
            ],
            'Executive Strategy' => [
                'strategy.view' => 'View executive strategy workspace',
                'strategy.manage' => 'Manage directives, decisions, and corporate risks',
            ],
            'Marketing and Communications' => [
                'marketing.view' => 'View marketing and communications workspace',
                'marketing.manage' => 'Manage marketing plans and content records',
            ],
            'Legacy Billing Records' => [
                'sales.view' => 'View legacy billing records',
                'sales.create' => 'Create legacy billing records',
                'sales.edit' => 'Edit legacy billing records',
                'sales.delete' => 'Delete legacy billing records',
                'sales.refund' => 'Process legacy refunds and reversals',
            ],
            'Inventory' => [
                'products.view' => 'View products',
                'products.manage' => 'Manage products',
                'inventory.view' => 'View stock',
                'inventory.adjust' => 'Adjust stock',
                'purchases.manage' => 'Manage purchases',
                'suppliers.manage' => 'Manage suppliers',
            ],
            'Customers & CRM' => [
                'customers.view' => 'View customers',
                'customers.manage' => 'Manage customers',
                'crm.accounts.view' => 'View CRM customer account workspace',
                'crm.accounts.manage' => 'Manage CRM customer accounts',
                'crm.timeline.view' => 'View customer communication and relationship timeline',
                'crm.health.view' => 'View customer health and account status',
                'crm.manage' => 'Manage legacy CRM',
            ],
            'Commercial Operations' => [
                'commercial.dashboard.view' => 'View commercial dashboard',
                'commercial.dashboard.executive' => 'View executive commercial dashboard',
                'commercial.campaigns.view' => 'View marketing and commercial campaigns',
                'commercial.campaigns.manage' => 'Manage marketing and commercial campaigns',
                'commercial.leads.view' => 'View leads',
                'commercial.leads.create' => 'Create leads',
                'commercial.leads.update' => 'Update leads',
                'commercial.leads.assign' => 'Assign leads',
                'commercial.leads.convert' => 'Convert leads',
                'commercial.organizations.view' => 'View commercial organizations',
                'commercial.organizations.create' => 'Create commercial organizations',
                'commercial.organizations.update' => 'Update commercial organizations',
                'commercial.stakeholders.view' => 'View stakeholders',
                'commercial.stakeholders.create' => 'Create stakeholders',
                'commercial.stakeholders.update' => 'Update stakeholders',
                'commercial.opportunities.view' => 'View opportunities',
                'commercial.opportunities.create' => 'Create opportunities',
                'commercial.opportunities.update' => 'Update opportunities',
                'commercial.opportunities.assign' => 'Assign opportunities',
                'commercial.opportunities.change_stage' => 'Change opportunity stages',
                'commercial.opportunities.close' => 'Close opportunities',
                'commercial.opportunities.handoff_to_sales' => 'Hand commercial opportunities to Sales',
                'commercial.opportunities.view_financials' => 'View opportunity financials',
                'commercial.activities.view' => 'View commercial activities',
                'commercial.activities.create' => 'Create commercial activities',
                'commercial.meetings.view' => 'View commercial meetings',
                'commercial.meetings.create' => 'Create commercial meetings',
                'commercial.site_visits.view' => 'View site visits',
                'commercial.site_visits.create' => 'Create site visits',
                'commercial.settings.manage' => 'Manage commercial settings',
                'commercial.reports.view' => 'View commercial reports',
                'commercial.reports.export' => 'Export commercial reports',
                'commercial.audit.view' => 'View commercial audit history',
            ],
            'Planning & Performance' => [
                'planning.dashboard.view' => 'View planning and performance dashboard',
                'planning.daily.view' => 'View personal daily workspace',
                'planning.daily.update' => 'Update assigned daily tasks and submit evidence',
                'planning.daily.assign' => 'Assign daily tasks to employees',
                'planning.daily.review' => 'Review employee daily task evidence',
                'planning.strategy.view' => 'View strategic pillars and objectives',
                'planning.strategy.manage' => 'Manage strategic pillars and objectives',
                'planning.workplans.view' => 'View corporate, department and individual workplans',
                'planning.workplans.manage' => 'Manage workplans, targets, allocations and assignments',
                'planning.approvals.manage' => 'Approve workplans and planning baselines',
                'planning.executive.view' => 'View company performance scorecards',
                'planning.audit.view' => 'View planning audit history',
            ],
            'Finance' => [
                'finance.dashboard.view' => 'View finance control centre',
                'finance.accounts.view' => 'View chart of accounts',
                'finance.budgets.view' => 'View budget control',
                'finance.budgets.manage' => 'Manage budget lines',
                'finance.transactions.view' => 'View financial transaction register',
                'finance.sync.manage' => 'Sync operating modules into Finance',
                'accounting.view' => 'View accounting',
                'accounting.manage' => 'Manage accounting',
                'banking.manage' => 'Manage banking',
                'budgets.manage' => 'Manage budgets',
                'reports.view' => 'View reports',
                'reports.export' => 'Export reports',
            ],
            'Human Resource' => [
                'hr.view' => 'View HR',
                'hr.manage' => 'Manage HR',
                'hr.command.view' => 'View HR command centre',
                'hr.structure.view' => 'View organization structure',
                'hr.structure.manage' => 'Manage departments and teams',
                'hr.positions.view' => 'View positions and job architecture',
                'hr.positions.manage' => 'Manage positions and job architecture',
                'payroll.manage' => 'Manage payroll',
            ],
            'Products and Delivery' => [
                'delivery.view' => 'View products, engineering releases and implementation projects',
                'delivery.manage' => 'Manage products, releases and implementation projects',
            ],
            'Engineering and Knowledge' => [
                'engineering.view' => 'View engineering and software development workspace',
                'engineering.manage' => 'Manage engineering backlog and quality records',
                'knowledge.view' => 'View knowledge and document management workspace',
                'knowledge.manage' => 'Manage knowledge records',
            ],
            'Customer Success and Governance' => [
                'customer_success.view' => 'View customer success and support',
                'customer_success.manage' => 'Manage customer success and support',
                'governance.view' => 'View governance and compliance',
                'governance.manage' => 'Manage governance and compliance',
            ],
            'Enterprise Intelligence' => [
                'intelligence.view' => 'View enterprise intelligence',
                'intelligence.manage' => 'Refresh and manage enterprise intelligence',
                'analytics.view' => 'View reports and analytics workspace',
                'analytics.manage' => 'Manage report definitions and analytics outputs',
            ],
            'Administration' => [
                'settings.view' => 'View settings',
                'settings.manage' => 'Manage company settings',
                'users.manage' => 'Manage users',
                'roles.manage' => 'Manage roles and permissions',
                'security.manage' => 'Manage security settings',
                'audit.view' => 'View audit logs',
            ],
        ];
    }

    public static function allKeys(): array
    {
        return array_keys(array_merge(...array_values(self::groups())));
    }

    public static function defaultRolePermissions(string $slug): array
    {
        return match ($slug) {
            'super_admin', 'admin' => self::allKeys(),
            'manager' => [
                'dashboard.view',
                'foundation.view',
                'foundation.notifications.view',
                'foundation.events.view',
                'strategy.view',
                'strategy.manage',
                'marketing.view',
                'marketing.manage',
                'commercial.campaigns.view',
                'commercial.campaigns.manage',
                'commercial.dashboard.view',
                'commercial.leads.view',
                'commercial.leads.create',
                'commercial.leads.update',
                'commercial.leads.assign',
                'commercial.leads.convert',
                'commercial.organizations.view',
                'commercial.organizations.create',
                'commercial.organizations.update',
                'commercial.stakeholders.view',
                'commercial.stakeholders.create',
                'commercial.stakeholders.update',
                'commercial.opportunities.view',
                'commercial.opportunities.create',
                'commercial.opportunities.update',
                'commercial.opportunities.assign',
                'commercial.opportunities.change_stage',
                'commercial.opportunities.handoff_to_sales',
                'commercial.activities.view',
                'commercial.activities.create',
                'commercial.meetings.view',
                'commercial.meetings.create',
                'commercial.site_visits.view',
                'commercial.site_visits.create',
                'planning.dashboard.view',
                'planning.daily.view',
                'planning.daily.update',
                'planning.daily.assign',
                'planning.daily.review',
                'planning.strategy.view',
                'planning.workplans.view',
                'planning.workplans.manage',
                'planning.approvals.manage',
                'planning.executive.view',
                'finance.dashboard.view',
                'finance.accounts.view',
                'finance.budgets.view',
                'finance.transactions.view',
                'finance.sync.manage',
                'delivery.view',
                'delivery.manage',
                'engineering.view',
                'engineering.manage',
                'customer_success.view',
                'customer_success.manage',
                'governance.view',
                'governance.manage',
                'knowledge.view',
                'knowledge.manage',
                'intelligence.view',
                'intelligence.manage',
                'analytics.view',
                'analytics.manage',
                'sales.view',
                'sales.create',
                'products.view',
                'inventory.view',
                'customers.view',
                'customers.manage',
                'crm.accounts.view',
                'crm.accounts.manage',
                'crm.timeline.view',
                'crm.health.view',
                'hr.command.view',
                'hr.structure.view',
                'hr.positions.view',
                'reports.view',
            ],
            'cashier' => [
                'dashboard.view',
                'sales.view',
                'sales.create',
                'customers.view',
            ],
            'accountant' => [
                'dashboard.view',
                'foundation.view',
                'foundation.notifications.view',
                'sales.view',
                'finance.dashboard.view',
                'finance.accounts.view',
                'finance.budgets.view',
                'finance.budgets.manage',
                'finance.transactions.view',
                'finance.sync.manage',
                'accounting.view',
                'accounting.manage',
                'banking.manage',
                'budgets.manage',
                'reports.view',
                'reports.export',
            ],
            'inventory_officer' => [
                'dashboard.view',
                'products.view',
                'products.manage',
                'inventory.view',
                'inventory.adjust',
                'purchases.manage',
                'suppliers.manage',
            ],
            default => ['dashboard.view'],
        };
    }

    public static function defaultRoles(): array
    {
        return [
            ['name' => 'Super Admin', 'slug' => 'super_admin', 'description' => 'Full workspace control including users, roles, security, and audit logs.'],
            ['name' => 'Admin', 'slug' => 'admin', 'description' => 'Administrative access for daily workspace configuration.'],
            ['name' => 'Manager', 'slug' => 'manager', 'description' => 'Operational oversight across sales, inventory, customers, and reports.'],
            ['name' => 'Billing Clerk', 'slug' => 'cashier', 'description' => 'Client billing record entry access for legacy transactions.'],
            ['name' => 'Accountant', 'slug' => 'accountant', 'description' => 'Accounting, banking, budgets, and financial reporting access.'],
            ['name' => 'Inventory Officer', 'slug' => 'inventory_officer', 'description' => 'Product, stock, purchases, and supplier access.'],
            ['name' => 'Viewer', 'slug' => 'viewer', 'description' => 'Read-only dashboard access.'],
        ];
    }
}
