<?php

namespace App\Support;

class PermissionCatalog
{
    public static function groups(): array
    {
        return [
            'Dashboard' => [
                'dashboard.view' => 'View dashboard',
                'dashboard.sensitive' => 'View sensitive figures',
            ],
            'Sales & POS' => [
                'pos.access' => 'Access POS',
                'sales.view' => 'View sales',
                'sales.create' => 'Create sales',
                'sales.edit' => 'Edit sales',
                'sales.delete' => 'Delete sales',
                'sales.refund' => 'Process refunds',
            ],
            'Inventory' => [
                'products.view' => 'View products',
                'products.manage' => 'Manage products',
                'inventory.view' => 'View stock',
                'inventory.adjust' => 'Adjust stock',
                'purchases.manage' => 'Manage purchases',
                'suppliers.manage' => 'Manage suppliers',
            ],
            'Customers & CRM' => [
                'customers.view' => 'View customers',
                'customers.manage' => 'Manage customers',
                'crm.manage' => 'Manage CRM',
            ],
            'Commercial Operations' => [
                'commercial.dashboard.view' => 'View commercial dashboard',
                'commercial.dashboard.executive' => 'View executive commercial dashboard',
                'commercial.leads.view' => 'View leads',
                'commercial.leads.create' => 'Create leads',
                'commercial.leads.update' => 'Update leads',
                'commercial.leads.assign' => 'Assign leads',
                'commercial.leads.convert' => 'Convert leads',
                'commercial.organizations.view' => 'View commercial organizations',
                'commercial.organizations.create' => 'Create commercial organizations',
                'commercial.organizations.update' => 'Update commercial organizations',
                'commercial.stakeholders.view' => 'View stakeholders',
                'commercial.stakeholders.create' => 'Create stakeholders',
                'commercial.stakeholders.update' => 'Update stakeholders',
                'commercial.opportunities.view' => 'View opportunities',
                'commercial.opportunities.create' => 'Create opportunities',
                'commercial.opportunities.update' => 'Update opportunities',
                'commercial.opportunities.assign' => 'Assign opportunities',
                'commercial.opportunities.change_stage' => 'Change opportunity stages',
                'commercial.opportunities.close' => 'Close opportunities',
                'commercial.opportunities.handoff_to_sales' => 'Hand commercial opportunities to Sales',
                'commercial.opportunities.view_financials' => 'View opportunity financials',
                'commercial.activities.view' => 'View commercial activities',
                'commercial.activities.create' => 'Create commercial activities',
                'commercial.meetings.view' => 'View commercial meetings',
                'commercial.meetings.create' => 'Create commercial meetings',
                'commercial.site_visits.view' => 'View site visits',
                'commercial.site_visits.create' => 'Create site visits',
                'commercial.settings.manage' => 'Manage commercial settings',
                'commercial.reports.view' => 'View commercial reports',
                'commercial.reports.export' => 'Export commercial reports',
                'commercial.audit.view' => 'View commercial audit history',
            ],
            'Planning & Performance' => [
                'planning.dashboard.view' => 'View planning and performance dashboard',
                'planning.strategy.view' => 'View strategic pillars and objectives',
                'planning.strategy.manage' => 'Manage strategic pillars and objectives',
                'planning.workplans.view' => 'View corporate, department and individual workplans',
                'planning.workplans.manage' => 'Manage workplans, targets, allocations and assignments',
                'planning.approvals.manage' => 'Approve workplans and planning baselines',
                'planning.executive.view' => 'View company performance scorecards',
                'planning.audit.view' => 'View planning audit history',
            ],
            'Finance' => [
                'finance.dashboard.view' => 'View finance control centre',
                'finance.accounts.view' => 'View chart of accounts',
                'finance.budgets.view' => 'View budget control',
                'finance.budgets.manage' => 'Manage budget lines',
                'finance.transactions.view' => 'View financial transaction register',
                'finance.sync.manage' => 'Sync operating modules into Finance',
                'accounting.view' => 'View accounting',
                'accounting.manage' => 'Manage accounting',
                'banking.manage' => 'Manage banking',
                'budgets.manage' => 'Manage budgets',
                'reports.view' => 'View reports',
                'reports.export' => 'Export reports',
            ],
            'Human Resource' => [
                'hr.view' => 'View HR',
                'hr.manage' => 'Manage HR',
                'hr.command.view' => 'View HR command centre',
                'hr.structure.view' => 'View organization structure',
                'hr.structure.manage' => 'Manage departments and teams',
                'hr.positions.view' => 'View positions and job architecture',
                'hr.positions.manage' => 'Manage positions and job architecture',
                'payroll.manage' => 'Manage payroll',
            ],
            'Administration' => [
                'settings.view' => 'View settings',
                'settings.manage' => 'Manage company settings',
                'users.manage' => 'Manage users',
                'roles.manage' => 'Manage roles and permissions',
                'security.manage' => 'Manage security settings',
                'audit.view' => 'View audit logs',
            ],
        ];
    }

    public static function allKeys(): array
    {
        return array_keys(array_merge(...array_values(self::groups())));
    }

    public static function defaultRolePermissions(string $slug): array
    {
        return match ($slug) {
            'super_admin', 'admin' => self::allKeys(),
            'manager' => [
                'dashboard.view',
                'commercial.dashboard.view',
                'commercial.leads.view',
                'commercial.leads.create',
                'commercial.leads.update',
                'commercial.leads.assign',
                'commercial.leads.convert',
                'commercial.organizations.view',
                'commercial.organizations.create',
                'commercial.organizations.update',
                'commercial.stakeholders.view',
                'commercial.stakeholders.create',
                'commercial.stakeholders.update',
                'commercial.opportunities.view',
                'commercial.opportunities.create',
                'commercial.opportunities.update',
                'commercial.opportunities.assign',
                'commercial.opportunities.change_stage',
                'commercial.opportunities.handoff_to_sales',
                'commercial.activities.view',
                'commercial.activities.create',
                'commercial.meetings.view',
                'commercial.meetings.create',
                'commercial.site_visits.view',
                'commercial.site_visits.create',
                'planning.dashboard.view',
                'planning.strategy.view',
                'planning.workplans.view',
                'planning.workplans.manage',
                'planning.approvals.manage',
                'planning.executive.view',
                'finance.dashboard.view',
                'finance.accounts.view',
                'finance.budgets.view',
                'finance.transactions.view',
                'finance.sync.manage',
                'sales.view',
                'sales.create',
                'products.view',
                'inventory.view',
                'customers.view',
                'customers.manage',
                'hr.command.view',
                'hr.structure.view',
                'hr.positions.view',
                'reports.view',
            ],
            'cashier' => [
                'dashboard.view',
                'pos.access',
                'sales.view',
                'sales.create',
                'customers.view',
            ],
            'accountant' => [
                'dashboard.view',
                'sales.view',
                'finance.dashboard.view',
                'finance.accounts.view',
                'finance.budgets.view',
                'finance.budgets.manage',
                'finance.transactions.view',
                'finance.sync.manage',
                'accounting.view',
                'accounting.manage',
                'banking.manage',
                'budgets.manage',
                'reports.view',
                'reports.export',
            ],
            'inventory_officer' => [
                'dashboard.view',
                'products.view',
                'products.manage',
                'inventory.view',
                'inventory.adjust',
                'purchases.manage',
                'suppliers.manage',
            ],
            default => ['dashboard.view'],
        };
    }

    public static function defaultRoles(): array
    {
        return [
            ['name' => 'Super Admin', 'slug' => 'super_admin', 'description' => 'Full workspace control including users, roles, security, and audit logs.'],
            ['name' => 'Admin', 'slug' => 'admin', 'description' => 'Administrative access for daily workspace configuration.'],
            ['name' => 'Manager', 'slug' => 'manager', 'description' => 'Operational oversight across sales, inventory, customers, and reports.'],
            ['name' => 'Cashier', 'slug' => 'cashier', 'description' => 'POS and sales entry access.'],
            ['name' => 'Accountant', 'slug' => 'accountant', 'description' => 'Accounting, banking, budgets, and financial reporting access.'],
            ['name' => 'Inventory Officer', 'slug' => 'inventory_officer', 'description' => 'Product, stock, purchases, and supplier access.'],
            ['name' => 'Viewer', 'slug' => 'viewer', 'description' => 'Read-only dashboard access.'],
        ];
    }
}
